name: Deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - ".github/**/*.yml"
      - "**.md"
      - "LICENSE"

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      REMOTE_USER: ${{ secrets.REMOTE_USER }}
      REMOTE_HOST: ${{ secrets.REMOTE_HOST }}

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $REMOTE_HOST >> ~/.ssh/known_hosts

      - name: Deploy Application
        run: |
          ssh -i ~/.ssh/id_rsa $REMOTE_USER@$REMOTE_HOST "cd /var/www && ./deploy.sh"
